Repository YETDA/frontend, pull requests merged in 2025-07, with the labels that each got.

#2 Tailwind CSS 기본 변수 설정
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/Header.tsx
  package-lock.json
  package.json
  public/images/sample-logo.png
  tailwind.config.ts
  tsconfig.json
Labels: style

#11 공통 컴포넌트 헤더, 서브헤더, 푸터 퍼블리싱 구현
  app/globals.css
  app/layout.tsx
  components/Footer.tsx
  components/Header.tsx
  components/SubHeader.tsx
  components/index.tsx
  public/images/sample-profile.png
Labels: style, asset, feat

#13 메인 페이지에서 사용할 캐러셀 퍼블리싱 구현
  app/components/HomeCarousel.tsx
  app/page.tsx
  app/testPage/page.tsx
  components/ui/button.tsx
  components/ui/carousel.tsx
  package-lock.json
  package.json
  public/images/sample-carousel-1.png
  public/images/sample-carousel-2.png
Labels: style, asset, feat

#16 메인 페이지에 최근 인기 프로젝트 퍼블리싱 구현
  app/components/ProjectCard.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/SubHeader.tsx
  components/ui/badge.tsx
  components/ui/card.tsx
  public/images/sample-card.png
  tailwind.config.ts
Labels: style, fix, asset, feat

#19 마이페이지 상단 프로필 영역 퍼블리싱
  app/my/components/Profile.tsx
  public/images/sample-image.jpg
Labels: style, asset, feat

#20 로그인 페이지 퍼블리싱 구현
  app/(guest)/login/layout.tsx
  app/(guest)/login/page.tsx
  app/(user)/components/HomeCarousel.tsx
  app/(user)/components/ProjectCard.tsx
  app/(user)/layout.tsx
  app/(user)/page.tsx
  app/layout.tsx
  components/Header.tsx
  public/images/github-login.png
  public/images/kakao-login.png
Labels: style, asset, feat

#21 검색 결과 페이지 퍼블리싱 구현
  app/(user)/search/page.tsx
Labels: style, feat

#24 padding 수정, tooltip 재설치
  app/(user)/layout.tsx
  components/Footer.tsx
  components/ui/tooltip.tsx
  package-lock.json
  package.json
Labels: style

#28 마이페이지에 프로필 깃허브 뱃지 추가
  app/(user)/my/components/GithubBadge.tsx
  app/(user)/my/components/Profile.tsx
Labels: style, feat

#38 토스 결제 연동 완료, 디렉토리 및 매개변수 수정 필요함
  app/api/test/TestApi.ts
  app/test/page.tsx
  app/toss/App.css
  app/toss/fail/page.tsx
  app/toss/page.tsx
  app/toss/success/page.tsx
  package-lock.json
  package.json
Labels: style, chore, feat

#43 헤더에서 로고 클릭시 메인으로 이동하게 수정
  components/Header.tsx
Labels: fix

#45 마이페이지 기능 통합 구현 및 API 연동 완료
  app/(user)/my/components/Follower.tsx
  app/(user)/my/components/Introduce.tsx
  app/(user)/my/components/Profile.tsx
  app/(user)/my/components/ProfileEditForm.tsx
  app/(user)/my/components/ui/MyProjectCard.tsx
  app/(user)/my/page.tsx
  app/api/my/useFollow.ts
  app/api/my/useFollowCount.ts
  app/api/my/useFollowing.ts
  app/api/my/useOrderList.ts
  app/api/my/usePurchase.ts
  types/user/orderList.ts
  types/user/purchaseProject.ts
Labels: fix, feat, refactor

#56 마이페이지 사용자 로그인 확인 로직 추가
  app/(user)/my/components/Profile.tsx
  app/(user)/my/components/ProfileEditForm.tsx
  app/(user)/my/components/ui/MyTextarea.tsx
  app/(user)/my/components/ui/MyTooltip.tsx
  app/(user)/my/page.tsx
  app/api/my/useFollow.ts
  app/api/my/useFollowCount.ts
  app/api/my/useFollowing.ts
  app/api/my/useOrderList.ts
  app/api/my/usePurchase.ts
Labels: feat, refactor

#59 로그인 확인 로직 삭제
  apis/my/useFollow.ts
  apis/my/useFollowCount.ts
  apis/my/useFollowing.ts
  apis/my/useOrderList.ts
  apis/my/usePurchase.ts
  apis/my/useUserOrderList.ts
  app/(guest)/login/layout.tsx
  app/(user)/my/page.tsx
  app/(user)/project/new/sell/page.tsx
  app/api/my/useCheckLogin.ts
  app/api/my/useHasHydrated.ts
  app/api/user/UserInfo.ts
  next.config.ts
  types/productFormData.ts
Labels: refactor

#60 토큰 프론트엔드 자체 쿠키 저장
  app/(guest)/login/page.tsx
  app/(user)/page.tsx
Labels: feat, refactor

#61 사용자 데이터 패치 오류 수정
  apis/dummyDonationProject.ts
  apis/dummySellProject.ts
  app/(user)/my/page.tsx
Labels: fix

#65 팔로우/언팔로우 API 연동 및 버튼 상태 관리 구현
  apis/my/ProfileApi.ts
  app/(user)/my/components/Follower.tsx
Labels: style, feat, refactor
